### ISSUE TITLE
Please consider default name change, gas -> energy

### ISSUE THREAD

**Issue by michalmie** [chomupashchuk/ariston-remotethermo-home-assistant#2]
Firstly, Kudos for a great work!

I can confirm that integration works with heat pump: Ariston Nimbus Flex 50s

Please consider changing default name for heating medium, gas -> energy

It would be more generic name for other heating sources (heat pump).

For Example
Ariston Gas for Heating use in last 24 hours  -> Ariston Energy for Heating use in last 24 hours

**Comment by chomupashchuk** [comment]
There is no documentation and lot of guessing involved (in fact those specific sensors are invalid in my configuration and were added when i found dedicated request in one of projects in github).

Just to be clear: are values correct (match official application) but instead of gas, it is electricity in your case?

**Comment by michalmie** [comment]
> Just to be clear: are values correct (match official application) but instead of gas, 
> it is electricity in your case?

That's correct

**Comment by chomupashchuk** [comment]
Then makes a lot of sense then. I'll rename sensors in the near future.

**Comment by chomupashchuk** [comment]
By the way, do "ch_account_gas" and "dhw_account_gas" provide valid values? 
24h and 7-30-365 days are handled in one way, but those two (marked "account") are a bit different.

in data received from gateway there are dedicated parameters (values from one of testers, where gas parameters are valid), so i wonder if new sensors have to be created for electricity.
    "account": {
        "gasHeat": 1424.0,
        "elecHeat": 0.0,
        "gasDhw": 341.0,
        "elecDhw": 0.0,
        "elecCooling": 0
    }
I use "store_config_files: true" in configuration.yaml to get json files for analysis. In case you are interested :)

**Comment by chomupashchuk** [comment]
Please check the latest version.
Note that some sensors renamed in configuration.yaml related to energy use.
