### ISSUE TITLE
Ariston Velis Wifi - LoginError

### ISSUE THREAD

**Issue by viotemp1** [chomupashchuk/ariston-remotethermo-home-assistant#3]
Hello,

I'm trying to use ariston-remotethermo-home-assistant custom component and I receive login errors. The password used in HA is good for sure - tested with their mobile app and on https://www.ariston-net.remotethermo.com/Account/Login
What can be wrong? My password is compliant with their requirements, having uppercase, lowercase, numbers and punctuation marks.
Error is:
2020-03-17 19:14:06 WARNING (SyncWorker_4) [custom_components.ariston] <custom_components.ariston.AristonChecker object at 0x7f479b1557d0> Authentication login error
2020-03-17 19:14:06 WARNING (SyncWorker_4) [custom_components.ariston] Boiler errors: 1
2020-03-17 19:14:06 ERROR (SyncWorker_4) [custom_components.ariston] Login error for Boiler:
2020-03-17 19:14:32 WARNING (SyncWorker_4) [custom_components.ariston] <custom_components.ariston.AristonChecker object at 0x7f479b1557d0> Authentication login error
2020-03-17 19:14:32 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ariston/__init__.py", line 768, in _get_unit_data
    self._get_http_data(REQUEST_GET_UNITS)
  File "/config/custom_components/ariston/__init__.py", line 637, in _get_http_data
    self._login_session()
  File "/config/custom_components/ariston/__init__.py", line 330, in _login_session
    raise LoginError
custom_components.ariston.exceptions.LoginError

**Comment by chomupashchuk** [comment]
Hi, 

Do you use quotation marks for email address and a password? Recommended to use them.
I know that at least 4 people have successfully logged in using custom component (based on feedback), so sounds strange.

**Comment by viotemp1** [comment]
I tried with/without quotation marks for username/pass. Still the same error

**Comment by chomupashchuk** [comment]
Error is reported when redirection from login page is not to "https://www.ariston-net.remotethermo.com/PlantDashboard/Index/....". I test all versions before uploading (at least basic test to get sensor data), so I'm stumbled.
You may check web version if redirected address matches mentioned above, also check configuration.yaml for correct number of spaces before each element (just in case). If address matches and configuration format is correct, I can upload new version, which shall store locally files on your system in /config folder of fetched login and password (shows what data actually fetched by integration, for you to check, as it is personal data) and exact reply that Home Assistant receives (http reply from the site).

Please let me know if there is a need for such updates.

**Comment by viotemp1** [comment]
Thanks for answer!
I'm redirected from web login to https://www.ariston-net.remotethermo.com/PlantManagement/Index/...
If you can upload a more verbose version, sure I want to check what's going on

**Comment by chomupashchuk** [comment]
new version is uploaded.
Please add following to configuration.yaml under `ariston:`
`store_config_files: true`

It shall enable files creation. Following files should be created under `/config` folder:
`login_Ariston_redirect_url.json`
`login_Ariston_reply.json`
`PERSONAL_login_Ariston_password.json`

Please check "PERSONAL_..." file to see if correct password is fetched by integration.
If file is not generated or data is empty in the file, then seems like fault is in configuration.yaml file.
If everything fine with this step, then please share `login_Ariston_reply.json` file, which is reply file from web server.

**Comment by chomupashchuk** [comment]
One more thing: there might be an issue if some special characters are used in the email (definitely not period or '@') or password, which might affect python in general. So if there are special characters, maybe try replacing them with some other special characters.

**Comment by viotemp1** [comment]
Unfortunately, no debug files are generated.
I use minimal config in /config/configuration.yaml:
ariston:
    username: "my_email"
    password: "my_pass"
    max_retries: 5
    store_config_files: true
    localization: 'en'
    name: Boiler
    switches:
        - power
        - internet_time
        - internet_weather
        - ch_auto_function

**Comment by chomupashchuk** [comment]
Just a question: are there 2 spaces before all elements except for 'ariston:' and 4 spaces before list of switches?

**Comment by chomupashchuk** [comment]
No file and login issue with correct data hints at configuration file, which should look like:
```
ariston:
  username: "user"
  password: "password"
  max_retries: 5
  name: 'Boiler'
  switches:
    - power
    - internet_time
    - internet_weather
    - ch_auto_function
```

**Comment by viotemp1** [comment]
I checked spacing, all OK ;like you said. Change password to have only one punctuation mark.
Still login error. And no debug files unfortunately.

**Comment by chomupashchuk** [comment]
i uploaded new version, which just creates files in /config folder, in your case they should look like:
login_Boiler_redirect_url.json
login_Boiler_reply.json
PERSONAL_login_Boiler_password.json

**Comment by viotemp1** [comment]
The files are generated now.
Can I share the file by email, looks like there are some info there that I don't want to be public.

**Comment by chomupashchuk** [comment]
chomu.nattsol@gmail.com

**Comment by chomupashchuk** [comment]
Login itself was fixed (accepted different redirection URL), but "Ariston Velis Wifi" uses different application and i'm not sure if same requests are used, so cannot guarantee proper communication.
If existing implementation shall not work (different requests/replies used) then reverse-engineering would be required for your model (as i did with mine). 

If communication shall not work (errors like timeouts or CommError or code 500 constantly and never successful communication) you may check "Guide_for_new_requests.doc" of how in general i found corresponding requests. I doubt that you would provide me with login and password to investigate it myself. If there is much in common, it could be integrated in this component, but as of now it is a black box.

**Comment by amans-git** [comment]
Hi @chomupashchuk 

The Ariston Velix WiFi doesn't seem to have the same infos in https://www.ariston-net.remotethermo.com/
Not to say almost no info ^^

![image](https://user-images.githubusercontent.com/46399510/82765024-96375f80-9e13-11ea-9eb6-f7a3f6ef52fd.png)

As you said, it's using another app.
I tried to reverse-engineering but I didn't managed it.

I could give you my user/password if you want to give it a try ?

Tell me :)
Thx

**Comment by amans-git** [comment]
Hi @chomupashchuk 

It seems the Ariston Velis Wifi doesn't work the same way.
As you said, it's not the same app.
And in https://www.ariston-net.remotethermo.com I've almost nothing.
Just some basic identification info in some tabs, others are empty.

![image](https://user-images.githubusercontent.com/46399510/82765167-9ab04800-9e14-11ea-901b-edb7d1f8c436.png)

I tried to reverse-engineering the app but without success
I could give you my login/pwd if you're OK to try ?

Thx
amans

**Comment by chomupashchuk** [comment]
Hi,

If there is no web version, not much I can do. I started this project
mainly because I was able to see unencrypted http messages via tools, which
is not the case with Android application for example.

**Comment by amans-git** [comment]
Hi,
Ok
So you're stuck at the same point than me ^^
Thx

**Comment by CarpeDiemRo** [comment]
@chomupashchuk 
Hi, I am trying to integrate an Ariston Altea but, unfortunately all my efforts were unsuccessful. 
I receive the following errors in Logs section
```
Error doing job: Future exception was never retrieved
17:53:03 – custom_components/ariston/__init__.py (ERROR) - message first occurred at 17:52:04 and shows up 3 times
<custom_components.ariston.AristonChecker object at 0xaf7e1c10> Invalid data received for Main
17:53:03 – Ariston (WARNING) - message first occurred at 17:52:04 and shows up 6 times
<custom_components.ariston.AristonChecker object at 0xaf7e1c10> Retrying in 90.0 seconds
17:52:56 – Ariston (WARNING)
Config entry for upnp not ready yet. Retrying in 80 seconds.
17:52:31 – config_entries.py (WARNING)
```
and all my entities are in **unavailable** state.

configuration.yaml
```

  username: 'password'
  password: 'user'
  max_retries: 10
  name: 'AAON'
  localization: 'en'
  hvac_off_present: 'true'
  hvac_off: 'summer'
  power_on: 'winter'
  store_config_files: 'true'
  control_from_water_heater: 'true'
  units: 'metric'
  polling_rate: 'normal'
```

Any idea?

**Comment by chomupashchuk** [comment]
Hi,

Integration emulates https://www.ariston-net.remotethermo.com  to some extent. Do you see needed data (like temperatures) when log in on the site?

**Comment by CarpeDiemRo** [comment]
This is what I see on the site
![Screenshot 2020-06-02 at 19 00 25](https://user-images.githubusercontent.com/38489167/83542328-771b8a80-a503-11ea-8b14-8b84b3bb974d.png)

**Comment by chomupashchuk** [comment]
I do not see DHW and CH temperatures. From my configuration:
![Capture](https://user-images.githubusercontent.com/50545689/83542860-3b34f500-a504-11ea-8d84-5142fce49eef.PNG)

Integration attempts to read both temperatures, which potentially can result in issues. 
Is it OK that only one temperature is available?

**Comment by CarpeDiemRo** [comment]
You are right. What should be done in order to have the same view as you have? In my situation, HA doesn't have anything available. 
![Screenshot 2020-06-02 at 19 17 36](https://user-images.githubusercontent.com/38489167/83543854-b9de6200-a505-11ea-8b39-e370517f0827.png)

**Comment by chomupashchuk** [comment]
Exception is triggered when reading/checking CH (central heating) data and as result nothing is propagated to HA.
This is the first time i see no CH data (zone) on web page, which means no data is provided to integration for CH. 
Note that climate.ariston is CH data and water_heater.ariston is DHW data, it seems like your boiler does not report CH data, which crashes all entities data read. 
Can it be that boiler incorrectly configured? For example one of guys noticed that his boiler switched mode for some unknown reason and no longer worked with external tank data.

Did you try to disconnect/connect power for boiler? Did you see CH data previously in android application or web version?

I can prepare prototype of integration to see what kind of data is actually being received from web to understand a bit more.

**Comment by CarpeDiemRo** [comment]
So, in conclusion, the first step is to create a zone. Right?

No, I have never seen a zone in Android or in WEB version. I really don't know how the central heating worked until now

**Comment by chomupashchuk** [comment]
Probably, i'm not an expert in those boilers to say something for sure. Just from experience what is shown on web page is available in integration, other data is often invalid (not always).

I'm attaching zip with "__init__.py" and that file can be replaced in custom_components/ariston folder. It creates file under "/config" folder named "main_data_from_web.json" to see what exactly is received from web page.

[__init__.zip](https://github.com/chomupashchuk/ariston-remotethermo-home-assistant/files/4718524/__init__.zip)

**Comment by CarpeDiemRo** [comment]
Thank you so much. These are the data that were received after I overwrite init.py

`{"mode": 1, "allowedModes": [0, 1, 5], "outsideTemp": 17.0, "holidayEnabled": false, "holidayUntil": "0001-01-01T00:00:00", "dhwTemp": {"min": 36.0, "max": 60.0, "value": 48.0, "prevValue": 0.0, "step": 0.0}, "flameSensor": false, "dhwDisabled": false, "zone": {"mode": {"allowedOptions": [], "value": 0}, "comfortTemp": {"min": 0.0, "max": 0.0, "value": 0.0, "prevValue": 0.0, "step": 0.0}, "desiredTemp": 0.0, "roomTemp": 0.0, "derogaTemp": {"min": 0.0, "max": 0.0, "value": 0.0, "prevValue": 0.0, "step": 0.0}, "derogaEnabled": false, "derogaUntil": null, "heatRequest": false, "heatRequestAir": false, "antiFreezeTemp": 0.0, "fireplaceEnabled": false, "fireplaceUntil": null, "pilotOn": false}, "isCoolingSupported": false, "isCoolingOnlySupported": false, "isHeatingSupported": false, "isHpSystem": false, "isHybridSystem": false, "heatingPumpResistorOn": false, "dhwStorageTemp": 0.0, "dhwBoilerPresent": false, "heatingPumpOn": false, "heatingPumpBoostDhw": false, "quietMode": false, "dhwReadOnly": true, "hasDhwStorageProbe": false, "weather": 0, "remoteControl": {"requestedOn": 0, "isAccepted": false, "expiresAfterMinutes": 0}, "flameForDhw": false, "isVmcOn": false, "isBoostVmcOn": false, "dehumidifyRequest": false, "extraVentilationRequest": false, "dhwTimeProgComfortTemp": {"min": 0.0, "max": 0.0, "value": 0.0, "prevValue": 0.0, "step": 0.0}, "dhwTimeProgEconomyTemp": {"min": 0.0, "max": 0.0, "value": 0.0, "prevValue": 0.0, "step": 0.0}, "dhwMode": 0, "dhwTimeProgSupported": false, "dhwTimeProgComfortActive": false, "isHvInputOff": false, "completionToken": "", "bmsActive": false, "pilotSupported": false, "cascadeSystemType": 0, "dhwModeNotChangeable": true}`

**Comment by surenz** [comment]
hi @chomupashchuk ,

I have Ariston Lydos Wifi water heater and it is not manageable through the web page of Ariston Remote Thermo.

But I can supply the API requests of the Android app Ariston NET Aque which are sniffed via Fiddler.

If you think it will be usefull to your project I can send them by e-mail (as there's some personal information and I'm not keen to disclose it here :) )

**Comment by chomupashchuk** [comment]
Hi,

Unfortunately i have less spare time of now, so not sure how much time i can spend.
A quick question: is data sniffed by Fiddler decoded (i mean if it is possible to see URLs, headers, payload in "{}")?
One of the reasons why i started project was available web application for Ariston Remote Thermo, where it is possible to connect Fiddler to Chrome sandbox and see decoded messages. Dealing with encryption is out of my league.

**Comment by surenz** [comment]
Yes, everything is decoded with plain text json payloads and I can see the exact data I see on the app itself. I'm not sure only how to authentication token is generated but you can have an idea :)

**Comment by chomupashchuk** [comment]
Since Velis and similar use different API it is not supported by this API and new API must be created for it instead. I do not have corresponding HW nor enough information to start development of new API.
