### ISSUE TITLE
_get_param invalid reply code 500

### ISSUE THREAD

**Issue by weusto** [chomupashchuk/ariston-remotethermo-home-assistant#4]
Hello,

I have a lot of error
![image](https://user-images.githubusercontent.com/16722682/82449818-15433580-9aac-11ea-88bf-d73b5f3d5171.png)

**Comment by chomupashchuk** [comment]
The integration works in a next way: it connects via http to the Ariston server, which connects to gateways in your network. Error code 500 can be reported in 2 cases:
1. server has problem connecting to gateway, which has nothing to do with integration
2. some data is not accepted in a request from the integration for the specific hardware.

Integration uses multiple requests to fetch or set data (simulates different HTML pages from Ariston website).
If connection to Ariston is working and other data is updated (like room temperature) and you constantly get errors only for "_get_param" then issue is in compatibility with specific hardware. But if no data at all is fetched then it would hint at connection error between gateway and the server.

Please describe in more details.

**Comment by weusto** [comment]
All data is recovered but I have an error all 3 minutes in log
![image](https://user-images.githubusercontent.com/16722682/82452662-df07b500-9aaf-11ea-953a-93bc066e0b42.png)

I think the error comes from the climate entity, because impossible to recover ch_comfort_temperature and ch_economy_temperature

My boiler is a Elco thision mini

**Comment by chomupashchuk** [comment]
If it was temporary, then it is most likely connection between server and boiler, which is not under control. I occasionally get errors for minutes-hours (sometimes firewall blocked packets in router, sometimes ariston server errors were suspected).
So if it recovers then it is rather "normal" behavior, integration can only monitor the status in this case.
